#!/usr/bin/env python3
"""Generate theme/dev/snippets/sbs-weekly-schedule.liquid from the graph.

The Weekly Website Fix schedule is rendered from content/content-graph.json →
challenges. A challenge is linked only when its article is actually
published in the weekly-fix blog (checked in Liquid at render time), so a
scheduled or draft challenge appears as "coming <date>" and never as a link
to a 404. Dates are rendered as written in the graph (store timezone,
Thursdays; validate-graph enforces the cadence).

    python3 scripts/build-weekly.py          # write
    python3 scripts/build-weekly.py --check  # exit 1 if stale
"""
import datetime
import html
import io
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "theme", "dev", "snippets", "sbs-weekly-schedule.liquid")


def esc(s):
    return html.escape(str(s), quote=True)


def build(chals):
    out = ["{%- comment -%}",
           "  GENERATED by scripts/build-weekly.py from content/content-graph.json — do not edit.",
           "  Lists every challenge in the series; links only the ones the blog has published.",
           "{%- endcomment -%}",
           "{%- assign wf_blog = blogs['weekly-fix'] -%}",
           '<ol class="sbs-wf__schedule">']
    for c in sorted(chals.values(), key=lambda c: c["number"]):
        d = datetime.date.fromisoformat(c["publish"])
        nice = d.strftime("%-d %B %Y")
        out.append("{%%- assign wf_a = wf_blog.articles | where: 'handle', 'weekly-fix/%s' | first -%%}" % c["handle"])
        out.append("{%%- unless wf_a -%%}{%%- assign wf_a = wf_blog.articles | where: 'handle', '%s' | first -%%}{%%- endunless -%%}" % c["handle"])
        out.append('<li class="sbs-wf__item">'
                   '<span class="sbs-wf__num">#%d</span> '
                   '{%%- if wf_a -%%}<a href="{{ wf_a.url }}">%s</a> <span class="sbs-wf__date">{{ wf_a.published_at | date: "%%-d %%B %%Y" }}</span>'
                   '{%%- else -%%}<span class="sbs-wf__coming">%s</span> <span class="sbs-wf__date">coming %s</span>{%%- endif -%%}'
                   '</li>' % (c["number"], esc(c["title"]), esc(c["title"]), esc(nice)))
    out.append("</ol>")
    return "\n".join(out) + "\n"


def main():
    with io.open(os.path.join(ROOT, "content", "content-graph.json"), encoding="utf-8") as fh:
        graph = json.load(fh)
    text = build(graph["challenges"])
    if "--check" in sys.argv:
        cur = io.open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if cur != text:
            print("sbs-weekly-schedule.liquid is stale: run python3 scripts/build-weekly.py")
            return 1
        print("sbs-weekly-schedule.liquid is current")
        return 0
    with io.open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("wrote %s" % os.path.relpath(OUT, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
