#!/usr/bin/env python3
"""Generate the Complete Site Builder Stack product image.

Same tokens, mark and grammar as generate-product-image.py and
generate-brand-assets.py, so all four product images read as one family.

The other three images depict one bundle's module grid. This one cannot: the
bundle is three products, and a grid of 267 files would be unreadable and
meaningless. It shows the three products as three panels in lifecycle order,
which is the thing the bundle is actually selling.

Every number is counted from the product directories rather than typed. An image
is the one place a stale count is invisible to every text-based check.

Prices are deliberately NOT drawn. An image cannot be regenerated by a price
change, and a picture asserting $197 after a price moved would be a misleading
price claim that no check could see.

Usage: generate-bundle-image.py <outputDir>
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = sys.argv[1] if len(sys.argv) > 1 else "assets"
os.makedirs(OUT, exist_ok=True)

BG       = (11, 13, 18)
SURFACE2 = (23, 27, 38)
BORDER   = (35, 42, 56)
TEXT     = (233, 236, 243)
MUTED    = (167, 176, 192)
DIM      = (125, 135, 152)
ACCENT   = (138, 166, 255)

FDIR = "/usr/share/fonts/truetype/dejavu"
SANS_B, MONO_B, MONO = "DejaVuSans-Bold.ttf", "DejaVuSansMono-Bold.ttf", "DejaVuSansMono.ttf"


def font(name, size):
    return ImageFont.truetype(os.path.join(FDIR, name), size)


def rr(draw, box, radius, fill=None, outline=None, width=1):
    draw.rounded_rectangle(box, radius=radius, fill=fill, outline=outline, width=width)


def draw_mark(d, x, y, size, bar_colour, gap_ratio=0.20):
    bar_h = size * 0.19
    gap = size * gap_ratio
    for i in range(3):
        top = y + i * (bar_h + gap)
        w = size * (1.0 - i * 0.18)
        rr(d, [x, top, x + w, top + bar_h], radius=bar_h / 2, fill=bar_colour)


PARTS = [
    ("BUILD", "Website Launch System", "Claude-Code-Website-Launch-System"),
    ("RANK", "SEO & Website Audit Toolkit", "Claude-Code-SEO-Website-Audit-Toolkit"),
    ("CONVERT", "Conversion & Revenue Toolkit",
     "Claude-Code-Conversion-Revenue-Optimization-Toolkit"),
]


def measure(dirname):
    """Files, words and top-level modules. Counted, never typed."""
    import re as _re
    p = os.path.join(ROOT, "product", dirname)
    if not os.path.isdir(p):
        raise SystemExit("missing product directory: %s" % p)
    files = words = 0
    for r, _dirs, fs in os.walk(p):
        for f in fs:
            files += 1
            if f.endswith(".md"):
                with open(os.path.join(r, f), encoding="utf-8", errors="ignore") as fh:
                    words += len(fh.read().split())
    modules = len([x for x in os.listdir(p)
                   if os.path.isdir(os.path.join(p, x)) and _re.match(r"^\d{2}-", x)])
    return files, words, modules


rows = [(stage, title, *measure(d)) for stage, title, d in PARTS]
total_files = sum(r[2] for r in rows)
total_words = sum(r[3] for r in rows)
total_modules = sum(r[4] for r in rows)

W, H = 1600, 1200
img = Image.new("RGB", (W, H), BG)
d = ImageDraw.Draw(img)

glow = Image.new("RGB", (W, H), BG)
gd = ImageDraw.Draw(glow)
for r in range(700, 0, -14):
    a = int(16 * (1 - r / 700))
    gd.ellipse([160 - r, -220 - r, 160 + r, -220 + r],
               fill=(BG[0] + a, BG[1] + a, min(255, BG[2] + int(a * 2.2))))
img = Image.blend(img, glow, 0.85)
d = ImageDraw.Draw(img)

PAD = 84
draw_mark(d, PAD, PAD + 6, 54, ACCENT)
d.text((PAD + 78, PAD + 14), "SITE BUILDER STACK", font=font(MONO_B, 26), fill=MUTED)

d.text((PAD, PAD + 96), "Complete", font=font(SANS_B, 76), fill=TEXT)
d.text((PAD, PAD + 182), "Site Builder Stack", font=font(SANS_B, 76), fill=TEXT)
d.text((PAD, PAD + 292),
       "%d modules  ·  %d files  ·  3 downloads" % (total_modules, total_files),
       font=font(MONO, 30), fill=ACCENT)

# Three panels, one per product, in lifecycle order.
TOP = PAD + 380
GAP = 24
PW = (W - PAD * 2 - GAP * 2) // 3
PH = 350

for i, (stage, title, files, words, modules) in enumerate(rows):
    x = PAD + i * (PW + GAP)
    rr(d, [x, TOP, x + PW, TOP + PH], radius=18, fill=SURFACE2,
       outline=ACCENT if i == 2 else BORDER, width=2 if i == 2 else 1)

    d.text((x + 26, TOP + 28), stage, font=font(MONO_B, 26), fill=ACCENT)
    d.line([x + 26, TOP + 74, x + PW - 26, TOP + 74], fill=BORDER, width=1)

    # Title wraps to at most three lines rather than being truncated: a product
    # name cut mid-word in an image looks like a rendering bug.
    words_in_title = title.split()
    line, lines = "", []
    for wd in words_in_title:
        trial = (line + " " + wd).strip()
        if d.textlength(trial, font=font(SANS_B, 30)) > PW - 52 and line:
            lines.append(line)
            line = wd
        else:
            line = trial
    lines.append(line)
    for j, ln in enumerate(lines[:3]):
        d.text((x + 26, TOP + 100 + j * 40), ln, font=font(SANS_B, 30), fill=TEXT)

    base = TOP + 100 + len(lines[:3]) * 40 + 34
    for j, line_text in enumerate((
            "%d modules" % modules,
            "%d files" % files,
            "~%s words" % format(round(words, -3), ","))):
        d.text((x + 26, base + j * 36), line_text, font=font(MONO, 23),
               fill=MUTED if j == 0 else DIM)

d.text((PAD, TOP + PH + 60),
       "Build it.  Rank it.  Convert it.",
       font=font(SANS_B, 46), fill=TEXT)
d.text((PAD, TOP + PH + 128),
       "Three downloads on one order.  Plain Markdown.  Nothing to install.",
       font=font(MONO, 26), fill=DIM)

# A quiet footer line so the lower third is not dead space. Counted, like
# everything else on the image.
d.text((PAD, H - PAD - 30),
       "sitebuilderstack.com", font=font(MONO, 24), fill=DIM)

path = os.path.join(OUT, "product-complete-stack.png")
img.save(path)
print("  product-complete-stack.png  %dx%d  -> %s" % (W, H, os.path.abspath(path)))
print("  counted: %d files, %s words across %d products"
      % (total_files, format(total_words, ","), len(rows)))
